DELETE http://localhost:8080/events/10/register
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQHRlc3QuY29tIiwiZXhwIjoxNzE5MDQ5NDU4LCJ1c2VySWQiOjJ9.9pZzeTNFoF97_pailUn4gPLd_LKXAr4YWnPDtuLhCdY
