POST http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QxQHRlc3QuY29tIiwiZXhwIjoxNzE5MDQ5Mzg3LCJ1c2VySWQiOjF9.GOw0xNnyw_WaNawXuGMFKiojd8ag05LaP82qEYbPY0Q

{
    "name": "Test event 45",
    "description": "A test event",
    "location": "A test location!!!!",
    "dateTime": "2025-01-01T15:30:00.000Z"
}