PUT http://localhost:8080/events/2
Content-Type: application/json

{
    "name": "event updated",
    "description": "updated description",
    "location": "A test location 2-updated",
    "dateTime": "2025-01-01T15:30:00.000Z"
}